AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "Gemfile"
    - "Gemfile.lock"
    - "config.ru"

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Lint/DuplicateBranch:
  Enabled: false
